# Generated by Django 6.0.3 on 2026-07-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_profile_pic_course_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_published',
            new_name='is_public',
        ),
    ]
