# Generated by Django 6.0.3 on 2026-07-27 10:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_published_course_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='file',
        ),
        migrations.RemoveField(
            model_name='note',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='note',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='note',
            name='original_filename',
        ),
        migrations.AlterField(
            model_name='note',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.course', verbose_name='course'),
        ),
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'gif', 'doc', 'docx', 'txt', 'md', 'zip', 'rar', 'ppt', 'pptx', 'xls', 'xlsx'])])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.note')),
            ],
        ),
    ]
